Repository Studio-Yandex-Practicum/RandomCoffeeBotTelegram, pull requests merged in 2023-09, with the labels that each got.

#17 Feature poetry
  .pre-commit-config.yaml
  setup.cfg
Labels: good first issue

#29 Проработал структуру, добавил скелет админки и моделей.
  .pre-commit-config.yaml
  README.md
  docs/codestyle.md
  setup.cfg
  src/admin_user/admin.py
  src/admin_user/apps.py
  src/admin_user/models.py
  src/admin_user/tests.py
  src/admin_user/views.py
  src/bot/admin.py
  src/bot/apps.py
  src/bot/models.py
  src/bot/tests.py
  src/bot/views.py
  src/core/asgi.py
  src/core/settings.py
  src/core/urls.py
  src/core/wsgi.py
  src/manage.py
Labels: enhancement

#23 Настроен github actions с проверкой линтерами
  .github/workflows/codestyle_linters.yml
Labels: enhancement

#32 Попытка поднять бота вместе с сервером
  .github/workflows/codestyle_linters.yml
  poetry.lock
  pyproject.toml
  src/bot/apps.py
  src/bot/bot.py
  src/bot/handlers.py
  src/core/asgi.py
  src/core/settings.py
Labels: enhancement

#38 Feature/try to run bot
  src/core/settings.py
Labels: bug

#41 added makefile to run the bot
  Makefile
Labels: enhancement

#40 Модели сущностей
  .github/workflows/codestyle_linters.yml
  .pre-commit-config.yaml
  src/admin_user/admin.py
  src/admin_user/migrations/0001_initial.py
  src/admin_user/models.py
  src/bot/admin.py
  src/bot/apps.py
  src/bot/bot_interface.py
  src/bot/migrations/0001_initial.py
  src/bot/models.py
  src/core/settings.py
Labels: enhancement

#53 Feature/update readme
  README.md
  docs/materials/briff.md
  docs/materials/instructions.md
Labels: documentation

#60 Линтер ruff
  .github/workflows/codestyle_linters.yml
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  ruff.toml
  setup.cfg
  src/bot/constants/messages.py
Labels: enhancement

#49 added hendler and inline for support
  src/admin_user/migrations/0001_initial.py
  src/bot/bot_interface.py
  src/bot/constants/links.py
  src/bot/constants/messages.py
  src/bot/handlers/command_handlers.py
  src/bot/keyboards/command_keyboards.py
  src/bot/migrations/0001_initial.py
Labels: enhancement

#75 Полная диаграмма логики бота согласно фичлисту
  docs/Diagramm of bot logic.jpg
  docs/Diagramm_of_bot_logic.drawio
Labels: documentation

#74 Feature/test commands
  src/tests/test_help.py
  src/tests/test_help_keyboard.py
  src/tests/test_redirection_to_support.py
  src/tests/test_start_keyboard.py
  src/tests/test_support.py
  src/tests/test_support_keyboard.py
Labels: enhancement

#61 Обработчики для go, выбор роли, в следующий раз
  src/bot/bot_interface.py
  src/bot/constants/buttons.py
  src/bot/constants/messages.py
  src/bot/constants/patterns.py
  src/bot/constants/states.py
  src/bot/handlers/command_handlers.py
  src/bot/handlers/conversation_handlers.py
  src/bot/keyboards/command_keyboards.py
  src/bot/keyboards/conversation_keyboards.py
  src/tests/test_help_keyboard.py
Labels: enhancement

#81 Утверждение имени пользователя
  src/bot/bot_interface.py
  src/bot/constants/messages.py
  src/bot/constants/patterns.py
  src/bot/constants/states.py
  src/bot/handlers/command_handlers.py
  src/bot/handlers/conversation_handlers.py
Labels: enhancement

#85 Тесты для хендлеров установки имени
  src/bot/handlers/conversation_handlers.py
  src/bot/keyboards/conversation_keyboards.py
  src/tests/conftest.py
  src/tests/test_conversation/__init__.py
  src/tests/test_conversation/test_change_name.py
  src/tests/test_conversation/test_guess_name_keyboard.py
  src/tests/test_conversation/test_send_name_message.py
  src/tests/test_conversation/test_set_new_name.py
  src/tests/test_help.py
  src/tests/test_redirection_to_support.py
  src/tests/test_start.py
  src/tests/test_start_keyboard.py
  src/tests/test_support.py
  src/tests/test_support_keyboard.py
Labels: enhancement

#90 Feature/registration
  Makefile
  poetry.lock
  pyproject.toml
  src/bot/bot_interface.py
  src/bot/constants/buttons.py
  src/bot/constants/messages.py
  src/bot/constants/patterns.py
  src/bot/constants/states.py
  src/bot/handlers/conversation_handlers.py
  src/bot/keyboards/conversation_keyboards.py
  src/bot/migrations/0004_changed_surname.py
  src/bot/models.py
Labels: enhancement
