Repository Studio-Yandex-Practicum/RandomCoffeeBotTelegram, pull requests merged in 2023-10, with the labels that each got.

#105 Feature/pair search docs
  docs/flowchart_search_pair.drawio
  docs/flowchart_search_pair.jpg
  docs/materials/briff.md
Labels: documentation

#114 Feature/factories student recruiter
  Makefile
  README.md
  poetry.lock
  pyproject.toml
  src/bot/factories.py
  src/bot/management/__init__.py
  src/bot/management/commands/__init__.py
  src/bot/management/commands/create_pair.py
  src/bot/management/commands/create_passedpair.py
  src/bot/management/commands/create_recruiter.py
  src/bot/management/commands/create_student.py
  src/bot/utils/filldb_command.py
Labels: enhancement

#113 Сохранение состояний и данных в Redis
  .gitignore
  docs/materials/featch_list.md
  infra/dev/docker-compose.stage.yaml
  poetry.lock
  pyproject.toml
  src/bot/bot_interface.py
  src/bot/persistence.py
  src/core/settings.py
Labels: enhancement

#111 added new handler tests
  pytest.ini
  ruff.toml
  src/core/asgi.py
  src/core/config/settings_base.py
  src/core/config/settings_for_tests.py
  src/core/wsgi.py
  src/manage.py
  src/tests/conftest.py
  src/tests/test_conversation/test_check_username.py
  src/tests/test_conversation/test_continue_name.py
  src/tests/test_conversation/test_go.py
  src/tests/test_conversation/test_next_time.py
  src/tests/test_conversation/test_profile.py
  src/tests/test_conversation/test_role_choice.py
  src/tests/test_conversation/test_send_profile_form.py
  src/tests/test_conversation/test_set_phone_number.py
Labels: enhancement

#123 Dockerfile для сборки образа, Workflow для сборки образа в Packages
  .github/workflows/build-and-push-github-packages.yml
  infra/dev/dev.Dockerfile
  infra/prod/docker-compose.prod.yaml
  infra/prod/prod.Dockerfile
  requirements/develop.txt
  requirements/production.txt
Labels: enhancement

#120 added log_sheduler, fixed logger, gitignore
  .gitignore
  src/bot/bot_interface.py
  src/bot/handlers/command_handlers.py
  src/bot/handlers/conversation_handlers.py
  src/bot/handlers/schedulers.py
  src/core/config/logging.py
  src/core/config/settings_base.py
  src/run_bot.py
Labels: bug, enhancement

#121 added choose profession
  .gitignore
  src/bot/admin.py
  src/bot/constants/buttons.py
  src/bot/constants/patterns.py
  src/bot/handlers/conversation_handlers.py
  src/bot/keyboards/conversation_keyboards.py
  src/bot/migrations/0004_changed_surname.py
  src/bot/migrations/0004_profession_professional_key.py
  src/bot/migrations/0008_add_profession.py
  src/bot/models.py
  src/bot/utils/pagination.py
  src/bot/utils/transliteration.py
  src/core/persistence_data/persistence_file
  src/tests/test_conversation/test_continue_name.py
  src/tests/test_conversation/test_profile.py
Labels: enhancement

#125 Feature/search pair
  src/bot/bot_interface.py
  src/bot/constants/links.py
  src/bot/constants/messages.py
  src/bot/constants/patterns.py
  src/bot/constants/states.py
  src/bot/handlers/conversation_handlers.py
  src/tests/conftest.py
  src/tests/test_conversation/test_go.py
Labels: enhancement

#136 added delete_user_and_send_message action in admin panel
  poetry.lock
  src/admin_user/actions.py
  src/bot/admin.py
  src/bot/bot_interface.py
  src/bot/constants/cases.py
  src/bot/constants/messages.py
  src/bot/handlers/conversation_handlers.py
  src/bot/utils/message_senders.py
  src/core/config/logging.py
Labels: bug, enhancement

#142 fix adding users in DB with big telegram_id
  src/bot/migrations/0001_initial.py
  src/bot/models.py
Labels: bug

#143 add reset_password
  .env.example
  Makefile
  src/admin_user/admin.py
  src/admin_user/apps.py
  src/admin_user/forms.py
  src/admin_user/signals.py
  src/admin_user/urls.py
  src/admin_user/utils/render.py
  src/admin_user/utils/reset_password.py
  src/admin_user/utils/users/registration.py
  src/admin_user/views.py
  src/core/config/settings_base.py
  src/core/urls.py
  src/templates/emailing/email.html
  src/templates/emailing/password_reset_email.html
Labels: enhancement

#145 Feature/edit admin panel
  src/admin_user/admin.py
  src/admin_user/views.py
Labels: enhancement
