Repository Studio-Yandex-Practicum/RandomCoffeeBotTelegram, pull requests merged in 2023-11, with the labels that each got.

#161 fixed double mails
  src/admin_user/signals.py
Labels: bug

#164 fix bug phone number
  src/bot/constants/messages.py
  src/bot/constants/patterns.py
  src/bot/handlers/conversation_handlers.py
  src/bot/utils/validate_phone.py
  src/tests/test_conversation/test_send_profile_form.py
  src/tests/test_conversation/test_set_phone_number.py
Labels: bug

#182 Удаление аккаунта в логической диаграмме
  README.md
  docs/Diagramm of bot logic.jpg
  docs/Diagramm_of_bot_logic.drawio
  docs/Diagramm_of_bot_logic.jpg
  docs/materials/briff.md
Labels: enhancement

#193 done refactoring
  mypy.ini
  poetry.lock
  pyproject.toml
  requirements/develop.txt
  src/admin_user/utils/render.py
  src/admin_user/utils/reset_password.py
  src/admin_user/utils/users/registration.py
  src/bot/constants/states.py
  src/bot/handlers/command_handlers.py
  src/bot/handlers/conversation_handlers.py
  src/bot/keyboards/conversation_keyboards.py
  src/bot/utils/message_senders.py
  src/tests/test_conversation/test_set_new_name.py
Labels: documentation

#175 added dashboards
  Makefile
  poetry.lock
  pyproject.toml
  requirements/develop.txt
  requirements/production.txt
  ruff.toml
  src/admin_user/apps.py
  src/bot/admin.py
  src/bot/apps.py
  src/bot/dashoboard_widgets.py
  src/bot/models.py
  src/core/config/settings_base.py
  src/core/fixture/admin_interface_theme_random_cofe_bot.json
  src/core/forms.py
  src/core/urls.py
  src/core/views.py
  src/templates/admin/app_list.html
  src/templates/admin/index.html
  src/templates/controlcenter/dashboard.html
  src/templates/material/admin/includes/app_content.html
  src/templates/material/admin/side_nav.html
Labels: enhancement
